version: '2'

services:
    public-server:
        image: nginx:alpine
        ports:
            - 80:80            
            - 443:443
        volumes:
            #- ./volume/public-server/nginx/initial-ssl_nginx.conf:/etc/nginx/nginx.conf
            - ./volume/public-server/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./volume/public-server/ssl/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - ./volume/public-server/ssl/www.nyzme.com/etc/letsencrypt/live/nyzme.com/fullchain.pem:/etc/letsencrypt/live/www.nyzme.com/fullchain.pem
            - ./volume/public-server/ssl/www.nyzme.com/etc/letsencrypt/live/nyzme.com/privkey.pem:/etc/letsencrypt/live/www.nyzme.com/privkey.pem
            - ./volume/public-server/nginx/letsencrypt:/data/letsencrypt
        restart: always

    nyzme-blog:
        depends_on:
            - public-server
        image: nginx:alpine
        volumes:
            - ./volume/nyzme-blog/html:/usr/share/nginx/html
        restart: always